"""Initial C6 schema, frozen independently of application model changes."""

from alembic import op
import sqlalchemy as sa

revision = "c6_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.Column("patient_ref", sa.String(length=128), nullable=True),
        sa.Column("locale", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("current_prompt", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("summary_ref", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "attachments",
        sa.Column("attachment_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.CheckConstraint("size_bytes >= 0", name="ck_attachment_size"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("attachment_id"),
        sa.UniqueConstraint("session_id", "attachment_id", name="uq_attachment_owner"),
    )
    op.create_index(
        op.f("ix_attachments_session_id"), "attachments", ["session_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("audit_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_index(
        op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("message_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.CheckConstraint("sequence >= 0", name="ck_messages_sequence"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
        sa.UniqueConstraint("session_id", "message_id", name="uq_messages_owner"),
        sa.UniqueConstraint(
            "session_id", "sequence", name="uq_messages_session_sequence"
        ),
    )
    op.create_table(
        "model_calls",
        sa.Column("call_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=128), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.CheckConstraint("input_tokens >= 0", name="ck_call_input"),
        sa.CheckConstraint("latency_ms >= 0", name="ck_call_latency"),
        sa.CheckConstraint("output_tokens >= 0", name="ck_call_output"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        op.f("ix_model_calls_session_id"), "model_calls", ["session_id"], unique=False
    )
    op.create_table(
        "slot_states",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("slot_id", sa.String(length=128), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("options", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("value", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "slot_id"),
    )
    op.create_table(
        "summary_versions",
        sa.Column("summary_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("sections", sa.JSON(), nullable=False),
        sa.Column("patient_questions", sa.JSON(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.Column("approved_at", sa.String(length=40), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "(approved_at IS NULL AND approved_by IS NULL) OR (approved_at IS NOT NULL AND approved_by IS NOT NULL)",
            name="ck_summary_approval",
        ),
        sa.CheckConstraint("version > 0", name="ck_summary_version"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("summary_id"),
        sa.UniqueConstraint("session_id", "version", name="uq_summary_version"),
    )
    op.create_table(
        "candidate_records",
        sa.Column("candidate_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("slot_id", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id", "slot_id"],
            ["slot_states.session_id", "slot_states.slot_id"],
        ),
        sa.PrimaryKeyConstraint("candidate_id"),
        sa.UniqueConstraint(
            "session_id", "slot_id", "candidate_id", name="uq_candidate_owner"
        ),
        sa.UniqueConstraint(
            "session_id", "slot_id", "fingerprint", name="uq_candidate_payload"
        ),
    )
    op.create_table(
        "slot_history",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.String(length=128), nullable=False),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("previous_value", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("previous_status", sa.String(length=32), nullable=False),
        sa.Column("new_value", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("new_status", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("at", sa.String(length=40), nullable=False),
        sa.CheckConstraint("sequence >= 0", name="ck_history_sequence"),
        sa.ForeignKeyConstraint(
            ["session_id", "slot_id"],
            ["slot_states.session_id", "slot_states.slot_id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "sequence"),
    )
    op.create_table(
        "source_references",
        sa.Column("source_id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("slot_id", sa.String(length=128), nullable=False),
        sa.Column("candidate_id", sa.String(length=32), nullable=True),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("attachment_id", sa.String(length=32), nullable=True),
        sa.Column("quote", sa.Text(), nullable=True),
        sa.Column("location", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.CheckConstraint(
            "(message_id IS NOT NULL AND attachment_id IS NULL) OR (message_id IS NULL AND attachment_id IS NOT NULL)",
            name="ck_source_one_origin",
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "attachment_id"],
            ["attachments.session_id", "attachments.attachment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "message_id"],
            ["messages.session_id", "messages.message_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "slot_id", "candidate_id"],
            [
                "candidate_records.session_id",
                "candidate_records.slot_id",
                "candidate_records.candidate_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "slot_id"],
            ["slot_states.session_id", "slot_states.slot_id"],
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    op.create_index(
        op.f("ix_source_references_session_id"),
        "source_references",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_source_references_session_id"), table_name="source_references"
    )
    op.drop_table("source_references")
    op.drop_table("slot_history")
    op.drop_table("candidate_records")
    op.drop_table("summary_versions")
    op.drop_table("slot_states")
    op.drop_index(op.f("ix_model_calls_session_id"), table_name="model_calls")
    op.drop_table("model_calls")
    op.drop_table("messages")
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_attachments_session_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("sessions")
    # ### end Alembic commands ###
